plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar

theme: minima
minima:
  skin: dark

social_links:
  - platform: github
    user_url: "https://github.com/blakete"
  - platform: linkedin
    user_url: "https://linkedin.com/in/blakete"
  - platform: google_scholar
    user_url: "https://scholar.google.com/citations?user=xiM0_6sAAAAJ&hl=en"

scholar:
  style: apa
  locale: en
  source: "./_bibliography"
  bibliography: "references.bib"

markdown: kramdown
kramdown:
  math_engine: mathjax
  
timezone: "America/New_York"
title: Blake's Notes
author:
  name: Blake Edwards
email: blakete@mit.edu
github_username: blakete

# Define collections
collections:
  wiki:
    output: true
    permalink: /:collection/:title/

# Navigation
header_pages:
  - notes.md
  - about.md
  - contact.md

google_analytics: G-JJKZZMF533
